name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      name:
        description: 'Name of feature (ie leaderboard-part2)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: |
        git checkout ${{ github.ref }}
        git checkout -b release/v${{ github.event.inputs.versionName }}-${{ github.event.inputs.name }} ${{ github.ref }}
    - name: Initialize mandatory git config
      run: |
       git config user.name ${{ github.actor }}
    - name: Change version number and name
      run: printf '\next.version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}-${{ github.event.inputs.name }}
    - name: Create pull request into main
      uses: peter-evans/create-pull-request@v3
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       branch: release/v${{ github.event.inputs.versionName }}-${{ github.event.inputs.name }}
       base: main
       title: v${{ github.event.inputs.versionName }} into main
       author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
       committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
       body: |
           Hi!
           This PR was created in response to a workflow.
    - name: Create Release and Tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: v${{ github.event.inputs.versionName }}
          commitish: release/v${{ github.event.inputs.versionName }}-${{ github.event.inputs.name }}
          release_name: Release ${{ github.event.inputs.versionName }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
