name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      name:
        description: 'Name of feature (ie leaderboard-part2)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: |
        git checkout ${{ github.ref }}
        git checkout -b release/v${{ github.event.inputs.versionName }}-${{ github.event.inputs.name }} ${{ github.ref }}
    - name: Initialize mandatory git config
      run: |
       git config user.name ${{ github.actor }}
    - name: Change version number and name
      run: printf '\next.version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}-${{ github.event.inputs.name }}
    - name: Create a pull request
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: release/v${{ github.event.inputs.versionName }}-${{ github.event.inputs.name }}
        base: main
        title: v${{ github.event.inputs.versionName }} into main
        body: |
           Hi!
           This PR was created in response to a workflow.
